### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by JosueAshton** [chris1111/WirelessAdapterCloverBigSur#1]
The icon color not change when theme type dark or light

How to fix?

**Comment by chris1111** [comment]
I wil fix this because on beta Big SUr wifi icon looks ok

**Comment by JosueAshton** [comment]
I have design icons in color white whith Illustrator and convert to icns, a replacements but is only fix for thene type dak

**Comment by chris1111** [comment]
https://github.com/chris1111/WirelessAdapterCloverBigSur/releases/tag/V2

**Comment by Tetoalb** [comment]
Hi , I have the nano Edimax on my tdaughters MacBook air , I disabled security and installed than rebooted like in the video but it didn't work.  Updated to the latest Big Sur. If someone could help me I will apreciate it, my email is superfixus@hotmail.com Thanks. All he homework is on this Mac air, i got it with broken wifi and bought the addapter. thanks again. Tony

**Comment by JosueAshton** [comment]
> Uninstall V1 then install V2
> let me know, this is the best I can do
> https://github.com/chris1111/WirelessAdapterCloverBigSur/releases/tag/V2

It doesn't work and it doesn't look good.
The icon looks too prominent in light theme and in dark it looks compressed.
Nothing to do with the official icon, the idea is that the icon changes tone, if it is a light theme it should be changed to color # 333 approximately and if it is a dark theme it should be #fff without putting a border because just as you have it, it is the same tone white with very sharp edges for both subjects.

Better I leave version 1 and add the white icns that I designed.
Until then thanks for trying and I will keep waiting for another version of WirelessAdapterCloverBigSur

**Comment by chris1111** [comment]
> > Uninstall V1 then install V2
> > let me know, this is the best I can do
> > https://github.com/chris1111/WirelessAdapterCloverBigSur/releases/tag/V2
> 
> It doesn't work and it doesn't look good.
> The icon looks too prominent in light theme and in dark it looks compressed.
> Nothing to do with the official icon, the idea is that the icon changes tone, if it is a light theme it should be changed to color # 333 approximately and if it is a dark theme it should be #fff without putting a border because just as you have it, it is the same tone white with very sharp edges for both subjects.
> 
> Better I leave version 1 and add the white icns that I designed.
> Until then thanks for trying and I will keep waiting for another version of WirelessAdapterCloverBigSur


do you have a working icon?
If yes share here I will test

**Comment by JosueAshton** [comment]
> do you have a working icon?
> If yes share here I will test

I only have the white icns, what I do is replace in the / Library / Application% 20Support / WLAN folder
But this is a manual and bad process to do, it would be excellent if you could achieve the theory of the subject change along with the tone of the icon
[icon_wifi.zip](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)

[https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)

**Comment by JosueAshton** [comment]
> > do you have a working icon?
> > If yes share here I will test
> 
> I only have the white icns, what I do is replace in the / Library / Application% 20Support / WLAN folder
> But this is a manual and bad process to do, it would be excellent if you could achieve the theory of the subject change along with the tone of the icon
> [icon_wifi.zip](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> 
> [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)

![Captura de Pantalla 2020-11-15 a la(s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)

it looks like this

**Comment by chris1111** [comment]
> > > do you have a working icon?
> > > If yes share here I will test
> > 
> > 
> > I only have the white icns, what I do is replace in the / Library / Application% 20Support / WLAN folder
> > But this is a manual and bad process to do, it would be excellent if you could achieve the theory of the subject change along with the tone of the icon
> > [icon_wifi.zip](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> 
> ![Captura de Pantalla 2020-11-15 a la(s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> 
> it looks like this

In Light mode its also work? show me please

**Comment by JosueAshton** [comment]
It doesn't work unless I manually change the black icns again
![Captura de Pantalla 2020-11-15 a la(s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186719-3e254a00-2720-11eb-9835-a978dcb22af9.png)

**Comment by JosueAshton** [comment]
> > > > tienes un icono de trabajo? 
> > > > Si es así, comparte aquí lo probaré
> > > 
> > > 
> > > Solo tengo los icns blancos, lo que hago es reemplazar en la carpeta / Library / Application% 20Support / WLAN 
> > > Pero este es un proceso manual y incorrecto, sería excelente si pudiera lograr la teoría del cambio de tema junto con el tono del icono 
> > > [icon_wifi.zip ](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> > 
> > 
> > ![Captura de Pantalla 2020-11-15 a la (s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> > se parece a esto
> 
> ¿En modo Light también funciona? Muéstrame por favor

No funciona a menos que vuelva a cambiar manualmente los icns negros
![Captura de Pantalla 2020-11-15 a la(s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186729-4da49300-2720-11eb-97dd-40a2bd8d96e2.png)

**Comment by JosueAshton** [comment]
> > > > do you have a working icon?
> > > > If yes share here I will test
> > > 
> > > 
> > > I only have the white icns, what I do is replace in the / Library / Application% 20Support / WLAN folder
> > > But this is a manual and bad process to do, it would be excellent if you could achieve the theory of the subject change along with the tone of the icon
> > > [icon_wifi.zip](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> > 
> > 
> > ![Captura de Pantalla 2020-11-15 a la(s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> > it looks like this
> 
> In Light mode its also work? show me please

It doesn't work unless I manually change the black icns again
![Captura de Pantalla 2020-11-15 a la(s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186737-60b76300-2720-11eb-82c4-2569fdf9073c.png)

**Comment by JosueAshton** [comment]
I guess you have to validate the resource change (icns) in the config.plist or something like that when the user changes the theme or the background changes the theme

**Comment by chris1111** [comment]
> > > > > do you have a working icon?
> > > > > If yes share here I will test
> > > > 
> > > > 
> > > > I only have the white icns, what I do is replace in the / Library / Application% 20Support / WLAN folder
> > > > But this is a manual and bad process to do, it would be excellent if you could achieve the theory of the subject change along with the tone of the icon
> > > > [icon_wifi.zip](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > > > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> > > 
> > > 
> > > ![Captura de Pantalla 2020-11-15 a la(s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> > > it looks like this
> > 
> > 
> > In Light mode its also work? show me please
> 
> It doesn't work unless I manually change the black icns again
> ![Captura de Pantalla 2020-11-15 a la(s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186737-60b76300-2720-11eb-82c4-2569fdf9073c.png)

it stay white?

**Comment by JosueAshton** [comment]
> > > > > > tienes un icono de trabajo? 
> > > > > > Si es así, comparte aquí lo probaré
> > > > > 
> > > > > 
> > > > > Solo tengo los icns blancos, lo que hago es reemplazar en la carpeta / Library / Application% 20Support / WLAN 
> > > > > Pero este es un proceso manual y incorrecto, sería excelente si pudiera lograr la teoría del cambio de tema junto con el tono del icono 
> > > > > [icon_wifi.zip ](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > > > > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> > > > 
> > > > 
> > > > ![Captura de Pantalla 2020-11-15 a la (s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> > > > se parece a esto
> > > 
> > > 
> > > ¿En modo Light también funciona? Muéstrame por favor
> > 
> > 
> > No funciona a menos que vuelva a cambiar manualmente los icns negros
> > ![Captura de Pantalla 2020-11-15 a la (s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186737-60b76300-2720-11eb-82c4-2569fdf9073c.png)
> 
> se queda blanco?

Yes it doesn't change

**Comment by chris1111** [comment]
> > > > > > > tienes un icono de trabajo?
> > > > > > > Si es así, comparte aquí lo probaré
> > > > > > 
> > > > > > 
> > > > > > Solo tengo los icns blancos, lo que hago es reemplazar en la carpeta / Library / Application% 20Support / WLAN
> > > > > > Pero este es un proceso manual y incorrecto, sería excelente si pudiera lograr la teoría del cambio de tema junto con el tono del icono
> > > > > > [icon_wifi.zip ](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > > > > > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> > > > > 
> > > > > 
> > > > > ![Captura de Pantalla 2020-11-15 a la (s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> > > > > se parece a esto
> > > > 
> > > > 
> > > > ¿En modo Light también funciona? Muéstrame por favor
> > > 
> > > 
> > > No funciona a menos que vuelva a cambiar manualmente los icns negros
> > > ![Captura de Pantalla 2020-11-15 a la (s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186737-60b76300-2720-11eb-82c4-2569fdf9073c.png)
> > 
> > 
> > se queda blanco?
> 
> Yes it doesn't change

So my Icon on V2 is better because is change I know its not the best solution but its work

**Comment by JosueAshton** [comment]
> I guess you have to validate the resource change (icns) in the config.plist or something like that when the user changes the theme or the background changes the theme



> > > > > > > > tienes un icono de trabajo? 
> > > > > > > > Si es así, comparte aquí lo probaré
> > > > > > > 
> > > > > > > 
> > > > > > > Solo tengo los icns blancos, lo que hago es reemplazar en la carpeta / Library / Application% 20Support / WLAN 
> > > > > > > Pero este es un proceso manual e incorrecto, sería excelente si pudiera lograr la teoría del cambio de tema junto con el tono del icono 
> > > > > > > [icon_wifi. zip ](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542426/icon_wifi.zip)
> > > > > > > [https://github.com/JosueAshton/WIFI-MENUBAR-ICNS-MACOS/blob/main/icon_wifi.zip](url)
> > > > > > 
> > > > > > 
> > > > > > ![Captura de Pantalla 2020-11-15 a la (s) 08 41 23](https://user-images.githubusercontent.com/15762305/99186457-67dd7180-271e-11eb-9f4e-379458bfc016.png)
> > > > > > se parece a esto
> > > > > 
> > > > > 
> > > > > ¿En modo Light también funciona? Muéstrame por favor
> > > > 
> > > > 
> > > > No funciona a menos que vuelva a cambiar manualmente los icns negros
> > > > ![Captura de Pantalla 2020-11-15 a la (s) 08 54 05](https://user-images.githubusercontent.com/15762305/99186737-60b76300-2720-11eb-82c4-2569fdf9073c.png)
> > > 
> > > 
> > > se queda blanco?
> > 
> > 
> > Si no cambia
> 
> Entonces, mi Icon en V2 es mejor porque es un cambio.Sé que no es la mejor solución, pero funciona.

In version 2 the white is kept but with a dark border to differentiate but it is still white while the rest of the icons change their tone according to the theme so it really is not a solution

**Comment by chris1111** [comment]
propose my a full functional Icon and I will integrate to the program

**Comment by JosueAshton** [comment]
> propongo mi un ícono funcional completo y lo integraré al programa

The program works excellent better than TPLink, the only thing that does not work is the icon color in bigSur

If you find a way to make it work, the icon theme would be 100%, I suppose it is some theme validation in the config.plist that within the content of the package for BigSur, the adobe cloud icon also presents that error but other apps for example CleanMyMac X if you change the theme.

then you have to find what is the configuration so that the icon color changes when changing the theme

**Comment by Tetoalb** [comment]
Hi , I have the nano Edimax on my tdaughters MacBook air , I disabled security and installed than rebooted like in the video but it didn't work. Updated to the latest Big Sur. If someone could help me I will apreciate it, my email is superfixus@hotmail.com Thanks. All he homework is on this Mac air, i got it with broken wifi and bought the addapter. thanks again. Tony


[Installer Log 15-Nov-2020.txt](https://github.com/chris1111/WirelessAdapterCloverBigSur/files/5542838/Installer.Log.15-Nov-2020.txt)

**Comment by chris1111** [comment]
Release 15 Nov 2020 Use of wifi icon blue while waiting for a solution
https://github.com/chris1111/WirelessAdapterCloverBigSur/releases/tag/V3

**Comment by JosueAshton** [comment]
> Versión 15 de noviembre de 2020 Uso del icono de wifi azul mientras espera una solución
> https://github.com/chris1111/WirelessAdapterCloverBigSur/releases/tag/V3
> 
> ![1](https://user-images.githubusercontent.com/6248794/99196897-1d2f1a00-275d-11eb-9ce0-d8e71a4642a7.png)
> ![2](https://user-images.githubusercontent.com/6248794/99196898-1dc7b080-275d-11eb-8835-bacd3b770ae8.png)

thank you, and I'll keep waiting
