### ISSUE TITLE
WebSocket port 5060 blocked

### ISSUE THREAD

**Issue by rolker-007** [chris1111/WirelessAdapterCloverBigSur#14]
Hi! I have TL-WN723, Hackintosh Ventura with Clover. 
csr-active-config = 0x000
System Integrity Protection status: enabled.

Internet working, but I have some problems.
Example: on site https://www.speedtest.net errors in console - WebSocket port 5060 blocked.
When I open YouTube videos everything start freezing and video doesn't play.
I have problems only in browsers.

Can you help me?

**Comment by chris1111** [comment]
No crashing here no issue on speedtest
![Screenshot 2023-07-11 at 05 33 43](https://github.com/chris1111/WirelessAdapterCloverBigSur/assets/6248794/4290f61d-300c-42fb-9113-9221a8bce22d)
App's work good SIP enable
Issue is from your side Config or somethings in your Install

**Comment by rolker-007** [comment]
Maybe you can advise what settings in config need to be checked?

**Comment by chris1111** [comment]
> Maybe you can advise what settings in config need to be checked?


We are not here to solve the problems of Hackintosh or real mac like OCLP User's having nothing particular on my test config I am showing you that the application has nothing to do with your problems
