### ISSUE TITLE
USB key not detected.

### ISSUE THREAD

**Issue by alucardxs** [chris1111/WirelessAdapterCloverBigSur#2]
Hello dude,

First thanks for your hard work.
I used to use your software with my hackintosh in Catalina and it was rocking !

Now I'm on Bigsur and it's not working anymore ... I installed the bigsur version, SIP disabled, secure boot model disabled too ... I've got the icon but it's like no USB wifi key is connected ... 

Any ideas ?

**Comment by chris1111** [comment]
More then 1000 USB adapter existe what is your
secure boot model as nothings to do with Clover

**Comment by Tetoalb** [comment]
I had the same problem, I installed the original driver again than after that installed Chris’s software and it worked.

Sent from my iPhone

On Nov 19, 2020, at 7:33 AM, chris1111 <notifications@github.com> wrote:

﻿

More then 1000 USB adapter existe what is your
secure boot model as nothings to do with Clover
